spring:
  devtools:
    restart:
      enabled: true #开启热部署
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/ldu?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
    type: com.zaxxer.hikari.HikariDataSource
  cache: false